

services:
  # Database service
  postgres:
    image: postgres:15-alpine
    container_name: linkit-db
    environment:
      POSTGRES_DB: linkit
      POSTGRES_USER: linkit_user
      POSTGRES_PASSWORD: linkit_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkit-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: linkit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - linkit-network
    restart: unless-stopped

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkit-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
      - redis
    networks:
      - linkit-network
    restart: unless-stopped
    command: sh -c "npx prisma generate && npm run dev"

volumes:
  postgres_data:
  redis_data:

networks:
  linkit-network:
    driver: bridge 